INSERT INTO blogful_articles (title,style,content)
VALUES
( 'First post!' , 'Interview' , 'lorem ipsum carrots, enhanced rebates. Born result abandoned advantageous for us to discover corrupt regular something ought to be. Attain: manufacturers. discomfort, but do not achieve this freedom? ' ),
( 'Second behind! ' , 'How-to' , ' lorem ipsum carrots enhanced rebates. When you exercise eagerness worthy of the encounter, we have a beneficial effect on other occasions, and easy work to follow quo. They obtain them! Fields times due to the . ' ),
( 'Third behind! ' , 'News' , ' lorem ipsum carrots, enhanced rebates. Can pleasure needs, rejects? Eager entire work is part of nature itself is worthy of careful they like and when. It is our existence on this question. ' ),
( 'Fourth post' , 'How-to' , 'lorem ipsum carrots enhanced rebates. Freedom result. With this however, can avoid the pain of labor these or criticize the entire pain is inaccessible, because like! -Does anyone nothing? ' ),
( 'Fifth post ' , 'News', 'lorem, very carrots enhanced rebates. Currently she runs so accepted things, but us. Excepturi pleasure only, labor services, we reject matter of time, an intense hatred rejects it please?' ) ,
( 'Sixth behind' , 'Listicle' , 'lorem ipsum carrots, enhanced rebates, but they do occaecat time and vitality, such as labor and obesity. Over the years come, who nostrud exercise, the school district work unless they aliquip from her consequat. Duis cillum, however, want to be a pain in the pleasure of football cupidatat flee from pain to find produces no resultant. Excepteur cupidatat blacks are not excepteur, is soothing to the soul, that is, they deserted the general duties of those who are to blame for your troubles. ' ),
( 'Seventh behind' , 'Listicle' , 'lorem ipsum carrots, carrots enhanced rebates. However amusement fault for not only accepted but the pain is so accept suffering? And a mistake so that they do not require flight?' ),
( 'Eigth behind ' , 'News' , 'lorem, very carrots enhanced rebates. Consequatur are happy to follow important to get blinded by the pleasure I carry messages which it rejects, worthy of a regular, I do not fault blocks and pains!' ),
( 'Ninth behind' , 'Story' , 'lorem ipsum carrots, carrots enhanced rebates. Dignissimos extremely painful, the film broke training to carry his encounter momentary pleasure, but quo symptoms? Things that any pain is not mistake them?' ),
( 'Tenth behind' , 'How-to' , 'lorem ipsum carrots enhanced rebates. Their discomfort denounce come tomato times the blind to only worse is bound to be great. This is the architect blinded bound to the pleasures that?' );